### ISSUE TITLE
Gambling contract

### ISSUE THREAD

**Issue by RadNi** [Gambleswap/gambleswap-core#2]
- [x] participate (GMB value, bet value) {Cost: GMB} make sure all the GMBs are burnt after this call, and move some parts to treasury address. Lock the users LP token
- [x] endTurn () onlyAdmin 
- [x] claim: check the turn is finished, and msg.sender actually won the game. Change the credit of msg.sender

**Comment by amirhmi** [comment]
- [ ] Wrtite tests
